package Telas;

/**
 *
 * @author nicol
 */
public class ViewUpdate extends javax.swing.JFrame {

    /**
     * Creates new form ViewUpdate
     */
    public ViewUpdate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PAINEL9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CARREGANDO = new javax.swing.JProgressBar();
        FECHAR = new javax.swing.JButton();
        ATUALIZAR = new javax.swing.JButton();
        LBL_CARREGANDO = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Verificar Atualização");
        setLocation(new java.awt.Point(300, 200));
        setUndecorated(true);
        setType(java.awt.Window.Type.POPUP);

        PAINEL9.setBackground(new java.awt.Color(45, 45, 45));
        PAINEL9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(154, 22, 150), 2, true));
        PAINEL9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PAINEL9.setNextFocusableComponent(ATUALIZAR);
        PAINEL9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Verificar Atualização");
        PAINEL9.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 13, 256, 75));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LOGO1.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        PAINEL9.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 120, 150));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Versão atual: 1.3.0");
        PAINEL9.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 130, 30));

        CARREGANDO.setBackground(new java.awt.Color(204, 0, 204));
        CARREGANDO.setForeground(new java.awt.Color(102, 102, 102));
        CARREGANDO.setBorderPainted(false);
        CARREGANDO.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CARREGANDO.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        CARREGANDO.setOpaque(true);
        CARREGANDO.setStringPainted(true);
        PAINEL9.add(CARREGANDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 380, 20));

        FECHAR.setBackground(new java.awt.Color(153, 153, 153));
        FECHAR.setText("Fechar");
        FECHAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FECHARActionPerformed(evt);
            }
        });
        PAINEL9.add(FECHAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 110, 30));

        ATUALIZAR.setBackground(new java.awt.Color(153, 153, 153));
        ATUALIZAR.setText("Atualizar");
        PAINEL9.add(ATUALIZAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 110, 30));

        LBL_CARREGANDO.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LBL_CARREGANDO.setForeground(new java.awt.Color(153, 153, 153));
        PAINEL9.add(LBL_CARREGANDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 200, -1));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setText("Verificar Atualização");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        PAINEL9.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PAINEL9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PAINEL9, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:                
        new Thread() {
            public void run() {
                for(int i=0; i<101; i++) {
                    try {
                        sleep(90);
                        CARREGANDO.setValue(i);
                        
                        if (CARREGANDO.getValue()<=15) {
                            LBL_CARREGANDO.setText("Conectando...");
                        } else if (CARREGANDO.getValue()<=25) {
                            LBL_CARREGANDO.setText("Verificando versão atual...");
                        } else if (CARREGANDO.getValue()<=45) {
                            LBL_CARREGANDO.setText("Atualizando repositórios...");
                        } else if (CARREGANDO.getValue()<=75) {
                            LBL_CARREGANDO.setText("Verificando banco de dados...");
                        } else if (CARREGANDO.getValue()<=98) {
                            LBL_CARREGANDO.setText("Carregando Patch");
                        } else if (CARREGANDO.getValue()<=100) {
                            LBL_CARREGANDO.setText("Sua versão é a mais recente!");
                        }
                    } catch(InterruptedException ex) {                        
                    }
                }
            }
        }.start();                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void FECHARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FECHARActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_FECHARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewUpdate().setVisible(true);                     
            }
        });
    }        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ATUALIZAR;
    private javax.swing.JProgressBar CARREGANDO;
    private javax.swing.JButton FECHAR;
    private javax.swing.JLabel LBL_CARREGANDO;
    private javax.swing.JPanel PAINEL9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    void setVisible() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}